alias d='docker $*'
alias dcom='docker-compose $*'
alias dmac='docker-machine $*'
alias dmac-ssh='docker-machine ssh $DOCKER_MACHINE_NAME'
alias denv='. docker-machine-env'
alias da='docker attach '
alias dmac-export='sh $ZSH/docker/machine_export.sh $*'
alias dmac-import='sh $ZSH/docker/machine_import.sh $*'
